### ISSUE TITLE
compiler for windows 10

### ISSUE THREAD

**Issue by ghost** [yeokm1/programming-win31#1]
Hi

I want to learn this book but have no idea what compiler I need and how to run it on windows 10

Thx

**Comment by yeokm1** [comment]
The compiler in this book is based on Visual C++ 1.52 which is a 16-bit version. It will not run natively on Win 10 x64 but may be possible for Win 10 x32.

Otherwise, you may consider OpenWatcom which has 32-bit and 64-bit versions which can run on modern 64-bit Windows.

**Comment by ghost** [comment]
What possibilities are there to run Visual C++ 1.52 on windows 10 64 bit or do I need a virtual machine then?

Can openwatcom still compile code from this book?

**Comment by yeokm1** [comment]
You can consider Winevdm to run 16-bit programs on 64-bit Windows but I have not tried that for Visual C++ 1.52. If you wish to use VC++ 1.52 on a modern Win 64-bit OS, my personal recommendation is to use a VM.

For OpenWatcom, I have not used it to write a Win 3.1 app before but it should be doable. Not sure how close it will be to the examples in the book but it should not be too far off as someone else has done it. https://www.dialup.net/wingpt/

**Comment by ghost** [comment]
Are you interested in trying open watcom and tell me how to compile a 16 bit exe of the first code example of the book?
I really don't know where to start :(

Do you think I can compile a 16 bit exe from within windows 10 using open watcom?

**Comment by yeokm1** [comment]
I don't have the time right now to do this. It depends on your level of programming experience and what is your purpose of working on this old platform. 

If you a novice, perhaps try starting on a more modern Windows/Mac/Linux platform with many resources online. If you are an experienced developer, then perhaps look at the wingpt example or approach it's author to see how is it done.

**Comment by ghost** [comment]
You think open watcom is probably more difficult then an old compiler like visual c++?

**Comment by yeokm1** [comment]
I don't know whether Openwatcom is more difficult than Visual C++ 1.52 for Win 3.1 app development as I have not tried it. Perhaps just try it yourself with plenty of information you can find online.

**Comment by ghost** [comment]
Can I maybe get your email to ask questions when i'm stuck with windows api?

**Comment by yeokm1** [comment]
Sorry, I'm not available for this due to heavy personal commitments. Please consult the book.
